---
- hosts: localhost
  user: nttadmin01
  tasks:
  - name: build petclinic docker image from Dockerfile
    command: docker build -t aashikarao/spring-petclinic-angularjs:{{ build_number }} .

  - name: create tag to push image onto dockerhub
    command: docker tag aashikarao/spring-petclinic-angularjs:{{ build_number }} aashikarao/spring-petclinic-angularjs:latest

  - name: login to dockerhub account
    command: docker login -u {{ docker_username }} -p {{ docker_password }}

  - name: push docker image
    command: docker push aashikarao/spring-petclinic-angularjs:{{ build_number }}

  - name: push docker image with latest tag
    command: docker push aashikarao/spring-petclinic-angularjs:latest

  - name: remove image from server
    command: docker rmi aashikarao/spring-petclinic-angularjs:{{ build_number }}

  - name: logout from dockerhub
    command: docker logout