---
- name: Deploy petclinic
  hosts: localhostt
  user: nttadmin01
  tasks:
    - name: Create deployment to 3 pods on Kubernetes
      command: kubectl apply -f /opt/kube-apps/petclinic-deployment.yaml

    - name: Expose petclinic app as a service
      command: kubectl apply -f /opt/kube-apps/petclinic-service.yaml