apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - port: 8083
      targetPort: 8083
  type: LoadBalancer
  externalIPs:
    - 10.0.2.38